### ISSUE TITLE
VOID description workflow

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#24]
# @cspayne writes:

It would be helpful to discuss what parts of the workflow it would be useful to automate.

Current workflow (from Theo):

> 1. Produce the RDF/XML "instances_of_the_provenancestatement_class.rdf"
    Store in uwlswd_datasets git repo.
    The dataset should describe itself as described in the void description of uwlswd dataset.
>2. Produce the DataCite metadata.
    Base it on the dataset description in uwlswd dataset.
    Store in uwlswd_metadata git repo.
>3. Start DOI
    Create draft DOI in DataCite.
    Load DataCite metadata created above.
>4. Insert the DOI as appropriate in the RDF/XML and DataCite metadata.
>5. Describe dataset in the git repo uwlswd_datasets [https://doi.org/10.6069/uwlib.55.a#uwSemWeb](https://urldefense.com/v3/__https://doi.org/10.6069/uwlib.55.a*uwSemWeb__;Iw!!K-Hz7m0Vt54!jLQ_zPtfwn9IazNAo4j4YFhK30ZtRC45q2jWzHdM8VeL2bWITB4Uv8jgFHLIx0cKVUG-BmWX0YA$) and in [https://doi.org/10.6069/uwlib.55.a](https://urldefense.com/v3/__https://doi.org/10.6069/uwlib.55.a*uwSemWeb__;Iw!!K-Hz7m0Vt54!jLQ_zPtfwn9IazNAo4j4YFhK30ZtRC45q2jWzHdM8VeL2bWITB4Uv8jgFHLIx0cKVUG-BmWX0YA$), but in the RDF/XML version. Insert the DOI as needed.
>6.  Produce alternate serializations of the above as appropriate:
    - instances_of_the_provenancestatement_class.html
      - edit the XSLTs in the git repo uwlswd (requires some path changes, that's all)
      - create rdf2rdfa-provenanceStatement.xsl
      - edit rdf2rdfa-table.xsl (no changes were needed actually)
      - edit schemaOrgMarkup.xsl (a path needed to be changed here)
    - then use baby Python script "[rdf-2-nt-ttl-json.py](https://urldefense.com/v3/__https://github.com/uwlib-cams/uwlswd/blob/main/py/rdf-2-nt-ttl-json.py__;!!K-Hz7m0Vt54!jLQ_zPtfwn9IazNAo4j4YFhK30ZtRC45q2jWzHdM8VeL2bWITB4Uv8jgFHLIx0cKVUG-fQ2jmrs$)"
        - instances_of_the_provenancestatement_class.ttl
        - instances_of_the_provenancestatement_class.jsonld
        - instances_of_the_provenancestatement_class.nt
        - void_description_of_the_dataset_university_of_washington_libraries_semantic_web_data.html
 - edit the XSLTs in the git repo uwlswd, edit rdf2rdfa-uwSemWeb, then baby python
        - void_description_of_the_dataset_university_of_washington_libraries_semantic_web_data.ttl
        - void_description_of_the_dataset_university_of_washington_libraries_semantic_web_data.jsonld
        - void_description_of_the_dataset_university_of_washington_libraries_semantic_web_data.nt
 Make sure all serializations are stored in the appropriate git repo
>7. Complete the DOI (add URL)
>8. Check links to the html pages (I needed to manually add links to alt serializations)
>9. Exchange with Github: push/pull uwlswd_datasets.
    - uwlswd
    - uwlswd_datasets
    - uwlswd_metadata
>10. Edit the libraries web site to include the new dataset.
>11. Make sure everything dereferences

# @briesenberg07 comments:

We are continuing to use the uwSemWeb dataset - see new dataset **Instances of the ProvenanceStatement Class** | https://doi.org/10.6069/uwlswd.2e2b-y833 . This would be an argument for writing code which can also handle updates to the uwSemWeb datasets ('partitions')...

**Comment by gerontakos** [comment]
Mostly because, originally, the uwlswd dataset was comprised of descriptions of DPLA entities, we considered the datasets unified description sets. They referenced one another, and we thought we needed to create some sort of representation of those "files" as related description sets. However, IMO, those relationship are represented in the data and do not need to be so thoroughly restated in further descriptions; at the same time, the datasets should have some metadata (which we always provide). I think we could eliminate that layer -- where we describe the "full" dataset -- and that may further simplify the workflow; also, the "full dataset" has grown beyond DPLA entities. In addition, the URIs were not correctly formulated; the uwlswd dataset should not be a hash URI: the dataset description should have the hash URI. So the whole "VoID" description can be re-thought. I would be in favor of having the descriptions "contained" in the file, the way we do elsewhere, using mostly dct properties, just to simplify the workflow. At the same time, we would be wise to accommodate descriptions of datasets that are not "contained" in the dataset files. That would require considerable discussion.

**Comment by briesenberg07** [comment]
2023-08-21 discussion:

- @gerontakos mentions that the new Instances of ProvenanceStatement describes itself, as the UWLSWD vocabs do
- @gerontakos and @briesenberg07 are both moving towards 'ditching' VoID - let each resource (SourceResource, Aggregation, etc.) describe itself! As the vocabs do...

**Comment by gerontakos** [comment]
By the way, it looks like I was incorrect about "instances_of_the_provenancestatement_class" as it appears to fully integrated into uwlib.55.a#uwSemWeb like all the other entity-based datasets.

**Comment by briesenberg07** [comment]
I believe that we have obviated this issue, because:

1. We have implemented additional data modelling for the VoID "Instances of (...)" datasets (see #43 )
2. This data modelling makes it possible to use the same workflow for these datasets as for any other dataset or vocabulary

@cspayne @gerontakos close this issue?

**Comment by briesenberg07** [comment]
No longer need to deal with this, see [above](https://github.com/uwlib-cams/uwlswd/issues/24#issuecomment-1815274442)
