### ISSUE TITLE
develop wiki

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#29]
- any essential guidelines for making and publishing an update to a UWLSWD resource
- an overview and essential information about code, important dependencies, etc.
- basic guidance for running the code to publish data

**Comment by cspayne** [comment]
- [ ] workflow for creating/updating datasets 
   - [ ] including running serialization script
- [ ] overview of serialization code and any other work automated through code
- [ ] standards for data creation (metadata, schema.org, etc.)

**Comment by gerontakos** [comment]
I made an agenda item for this for 8/14 (didn't know it was an Issue at the time). So it looks like we plan to put everything in the wiki. That seems fine. Maybe we could work on adding details to the outline above? Would that be helpful or us as we build the wiki?

**Comment by gerontakos** [comment]
I used main.py earlier today for the first time. It's great. It will improve our lives tremendously and I'm thrilled.

For the record, I followed [03_update_resource_workflow](https://github.com/uwlib-cams/uwlswd/wiki/03_update_resource_workflow) with little recourse to [04_workflow_details](https://github.com/uwlib-cams/uwlswd/wiki/04_workflow_details), so I may have missed some important information in the latter document.

Anyway, in  [03_update_resource_workflow](https://github.com/uwlib-cams/uwlswd/wiki/03_update_resource_workflow), section 5, it doesn't state explicitly that the user of main.py has to manually change the value of the variable. Of course this may be me being dense, but it says "ensure that the .. variable is set to the correct value." So I was unsure: do they really want me to edit their code? And if so, what do I do with that change in the uwlswd git repo? Add and commit the change? Put it back in its original state? Use some other git instrument, like git -- checkout to eliminate my change? So that was an area where I stumbled.

Of course, as everyone would expect, I had trouble with paths. main.py prompts for values (saxon info and path to rdf/xml). I assumed quotes around all values were required; they were not. In fact, I think (at least with the rdf/xml path) quotes were harmful. In the examples in the main.py prompts, all values, including paths, are bound by quotes. So I was thinking, if I'm correct, this could be clarified in the wiki and in the code. Maybe.

I didn't play around with the slashes, but on first attempt, I thought using windows-style back-slashes would be fine. I used back-slashes and they failed. At least I know they failed for accessing the RDF/XML. When I used forward-slashes, that worked fine. (Forward slashes with no quotes: that was the only problem I had.) So I don't know if this should be addressed in either the code-prompts or the wiki. People choose their O/S's and I think it's fair to expect them to know how to render paths in their O/S. If we're super nice, we can make it explicit in the guidelines...

**Comment by cspayne** [comment]
Thank you Theo!

> Anyway, in [03_update_resource_workflow](https://github.com/uwlib-cams/uwlswd/wiki/03_update_resource_workflow), section 5, it doesn't state explicitly that the user of main.py has to manually change the value of the variable. Of course this may be me being dense, but it says "ensure that the .. variable is set to the correct value." So I was unsure: do they really want me to edit their code? And if so, what do I do with that change in the uwlswd git repo? Add and commit the change? Put it back in its original state? Use some other git instrument, like git -- checkout to eliminate my change? So that was an area where I stumbled.

I just added an input prompt in main.py so you no longer need to edit the code directly. When running main.py, the user will be asked if they would like to generate schema.org data from the rdf/xml. If yes, that xsl script is run. If no, the other script which generates Schema.org from DataCite metadata is run instead. Hopefully this clears up any complications while we are using both of these methods. 

> Of course, as everyone would expect, I had trouble with paths. main.py prompts for values (saxon info and path to rdf/xml). I assumed quotes around all values were required; they were not. In fact, I think (at least with the rdf/xml path) quotes were harmful. In the examples in the main.py prompts, all values, including paths, are bound by quotes. So I was thinking, if I'm correct, this could be clarified in the wiki and in the code. Maybe.

I've removed the quotations in the prompts. 

> I didn't play around with the slashes, but on first attempt, I thought using windows-style back-slashes would be fine. I used back-slashes and they failed. At least I know they failed for accessing the RDF/XML. When I used forward-slashes, that worked fine. 

Benjamin brought this up as well. I added code that _should have_ still produced the correct URIs even using back-slashes. Was the script unable to find the files when you used back-slashes? This may be related to the OS library which is used to navigate the file system. I don't currently have Python set up on my Windows system (although I really should get that set up soon), so I am not able to test this myself.

**Comment by gerontakos** [comment]
Those solutions should fix my problems. As for the slashes, I saw the replace \ with / method in the code and was wondering why my backslashes didn't work. Then I started to doubt that I did it correctly -- I wasn't being careful. Next time I run it, I'll check more methodically. I'll let you know.
