### ISSUE TITLE
Handling missing Schema.org values

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#58]
- There are some values that we can expect to always be present: id, name, etc.
- For those that are missing in some resources currently (although they may be present in resources going forward) - do we want to:
   - Omit these properties and values from the html (meaning the schema.org still has all the correct values but may be missing some properties we would like to have) and print to command line those that are missing (CP is leaning towards this option)
  - Keep these properties in schema.org but with a placeholder value (e.g. VALUE MISSING) so users can check and see based on output
  - Both keep the properties with a placeholder value and print to command line what values are missing

**Comment by cspayne** [comment]
Also similarly with DataCite metadata - should we use 'VALUE MISSING' placeholders, or not include that element?
If we do not include the element, this prevents the DataCite metadata from being uploaded when required values are missing, rather than it being uploaded with 'VALUE MISSING' literals.

**Comment by gerontakos** [comment]
For schema.org, omitting is fine. The message to standard output is helpful. It's like, Dear Esteemed Data Inputter, you are missing some key players but the show must go on, do what you must. The datacite situation is a little different because of the required properties. In that case, the placeholders are useful if the Inputter is going to edit the datacite xml directly. However, if the inputter wants to get the required data into the RDFXML and re-run the script, the placeholders have limited value that might have been better served with info immediately appearing at the command line. So. I personally would expect to edit the RDFXML, in which case I'd prefer to get my warning of missing and required properties at the command line, then, for missing but not required, just omit (or send a less dramatic message to the command line, like with the schema.org). In other words, treat the missing properties the same for schema and datacite, except for datacite-required, which should result in an extra bold warning that the properties are needed, add them to the RDFXML and re-run the script. Ya?

**Comment by cspayne** [comment]
New thought: 
Missing required properties will be caught with the rdf2datacite workflow, and the serialization workflow shouldn't be run until after the DataCite metadata generation. Schema.org metadata uses the same elements as DataCite with the exception of schema:version, so I believe that is the only element that the Schema.org process should inform the user on if it is missing (and this will become redundant if we ever implement validation for the rdf/xml)

**Comment by cspayne** [comment]
Proposal:
- rdf2datacite outputs warnings for missing elements required by our guidelines. If the element is required by DataCite as well, this gets an **emphasized warning**. 
- rdf2schema only outputs a warning if schema:version is missing. All other properties that we require by our guidelines (and that are used in Schema.org) will be caught in the DataCite workflow.

**Comment by briesenberg07** [comment]
@briesenberg07 will be running rdf2datacite and main.py/rdf2schema next week and will add any applicable comments then, but this sounds good to me and I have no suggested changes at the moment!
